### ISSUE TITLE
강의 목록 검색창 Throttling 기법 적용

### ISSUE THREAD

**Issue by wooojini** [koreatech/hanpyo#126]
## 💁 설명

강의 목록 검색창에 Throttling 기법을 적용하여 검색어 타이핑시 아래 강의 목록 결과가 바뀌도록 한다.

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- [x] Throttling 함수 제작
- [x] 검색창 이벤트에  Throttling 함수 적용

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 검색창 이벤트에  Throttling 함수 적용시 특정 순간에 필터링 결과가 보여지는데 성능을 테스트해보자

**Comment by jinhyukoo** [comment]
이 부분은 최적화를 좀 하고 기능을 추가하면 더 좋을 것 같다는 생각이었는데 생각해보니 검색어로 찾아서 나오는 강의가 많지 않아서 바로 적용시켜도 큰 상관 없을 듯 하네용 ㅎㅎㅎ
