### ISSUE TITLE
Select Box 컴포넌트 구현

### ISSUE THREAD

**Issue by Do-ho** [koreatech/hanpyo#3]
## 💁 설명

이슈 설명

![image](https://user-images.githubusercontent.com/33643752/106711302-aeb27780-663a-11eb-9c0e-4034bf9b78a4.png)

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- [ ] UI 제작
- [ ] 메뉴 펼치기
- [ ] Medium, Small Size 구현

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 재사용 가능한 컴포넌트로 만들어주세요!

**Comment by jinhyukoo** [comment]
#35 관련이슈 새롭게 파진 관계로 close
