### ISSUE TITLE
증식하는 style 태그 없애기

### ISSUE THREAD

**Issue by jinhyukoo** [koreatech/hanpyo#37]
## 💁 설명

현재 알 수 없는 이유로 style 태그가 계속해서 늘어나는 현상이 발생하고 있다.  
성능 개선을 위해 이를 해결하자.

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- [x] style 태그 생기는 원리 파악
- [x] style 태그 증식 못하게 막기

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

**Comment by jinhyukoo** [comment]
원인1. Box 컴포넌트
원인2. makeStyles API

**Comment by wooojini** [comment]
**증식하는 Style Tag 원인 분석 내용**
- **Material-UI는 내부적으로 CSS-in-JS 방식의 [jss](https://cssinjs.org/?v=v10.6.0) 라이브러리를 사용**.
   - Style 태그를 삽입하여 적용하는 방식
   - 정적 스타일은 head 태그의 style 태그안에 바로 삽입하여 한번 삽입 후, 제거하지 않고 재사용함
   - 동적 스타일은 style 태그를 삽입시키나 태그안에 내용이 있는 것이 아닌 stylesheet에 바로 적용함.
   - 동적 스타일은 props에 의해 런타임에 결정되는 동적인 스타일로 매번 유니크한 클래스 이름을 부여하여 생성함.
   - 컴포넌트 언마운트시 유니크하게 생성되는 스타일( 비어보이는 style 태그, document.stylesheet 내용)이 제거됨
   - 문제는 컴포넌트 렌더링시 불필요한 동적 스타일이 생성되고, 언마운트시 불필요한 부분이 제거가 안되어 마치 증식하는 것 처럼 느껴지는 문제 발생
- **withStyles(HOC 방식), styled(Styled Component 방식)은 단순히 문법적인 제공을 위한 API로 내부에서 makeStyles를 호출**
   - makeStyles에서는 attach, detach 함수를 통해 스타일을 적용.
   - 동적 스타일, 정적 스타일에 따른 별도 처리
   - 문제는 attach시 불필요한 스타일이 왜 추가되는지 의문.
- **예비 해결책**
   - 동적인 스타일링만 불필요한 스타일이 추가되므로, makeStyles로 정적인 스타일만 처리 후, 동적인 스타일은 인라인 스타일로 적용
      - 인라인 스타일은 기존 css 문법에 의한 한계점이 존재 (부모 선택자, 중첩 셀렉터 등)
   - styled component로 마이그레이션
      - material-ui를 이용해 빠르게 뷰를 완성하자는 취지에 어긋남. 마이그레이션과 동시에 컴포넌트 직접 제작 비용 발생
   - styled component + material-ui 통합 사용
      - makeStyle과 같은 material-ui 스타일링 솔루션 패키지를 사용하지 않고, styled component를 이용하는 방법
      - 불필요하게 styled component를 사용하는 것이 아닌가하는 의문점이 남음. 동적 스타일이 제거되지 않은 이슈는 현재 사례가 없다... 좀 더 근본적인 원인이 있을 것이라 예상

=> 일단 프로덕션 빌드시에도 동일한 문제가 발생하는지 검토 후, 다시 회의하기로 결정 

관련 서치 링크
- [material-ui style 패키지 소스](https://github.com/mui-org/material-ui/tree/next/packages/material-ui-styles/src)
- [jss 라이브러리 코어 API](https://cssinjs.org/jss-api?v=v10.6.0)
- [비슷한 이슈 - makeStyles API creates thousands of <style> tags synchronously](https://github.com/mui-org/material-ui/issues/16756)

**Comment by wooojini** [comment]
Material-UI 내부적으로 production 빌드시 다르게 동작하여 배포 상태에서 확인결과 증식하지 않아서 이슈 close.
