### ISSUE TITLE
시간표 인터렉션 기능 변경

### ISSUE THREAD

**Issue by wooojini** [koreatech/hanpyo#61]
## 💁 설명

시간표 인터렉션 기능 변경

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- [x] 강의목록 클릭 시, 시간표에 해당 강의 시간이 하이라이팅
      - 해당 강의의 다른 분반의 시간도 같이 하이라이팅
- [x] 강의목록 더블 클릭 시, 시간표 데이터 추가

**Comment by jinhyukoo** [comment]
Todo
1. 클릭시 해당 Row 강조 해줘야 하는데 어떤 식으로 로직 짤 것인지
2. 다른 곳 클릭시 하이라이팅 됐던 것 제거

**Comment by jinhyukoo** [comment]
Issue
1. 해당 기능에 대해서도 Style Tag 증식 문제 있음
